name: 'Setup SSH for EC2'
description: 'Setup SSH for connecting to an EC2 instance'

inputs:
  EC2_SSH_PRIVATE_KEY:
    description: 'The private key of EC2 instance for SSH connection'
    required: true
  EC2_URL:
    description: 'The URL of the EC2 instance'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup SSH for EC2
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H "${{ inputs.EC2_URL }}" >> ~/.ssh/known_hosts
