name: 'Set up SSH for EC2'
description: 'Set up SSH for connecting to an EC2 instance'

inputs:
  EC2_SSH_PRIVATE_KEY:
    description: 'The private key of EC2 instance for SSH connection'
    required: true
  EC2_URL:
    description: 'The URL of the EC2 instance'
    required: true

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH for EC2
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H $EC2_URL >> ~/.ssh/known_hosts
